on:
  workflow_dispatch:
    inputs:
      dispatch_token:
        description: 'Token that authorize the dispatch'
        required: true
      head_sha:
        description: 'Head commit SHA that dispatched the workflow'
        required: true

jobs:
  evaluator:
    runs-on: self-hosted
    steps:
      - name: Check out project repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: Checkout protected files
        uses: betrybe/blocked-files-checkout-action@v1
        with:
          restore_branch: 'main'
      - name: Run ESLint evaluator
        uses: betrybe/eslint-linter-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Jest evaluator
        id: test
        uses: betrybe/jest-evaluator-action@v8
      - name: Run Store evaluation
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.test.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.number }}